main(): Give the FastCGI closure access to the DB connection pool
Otherwise we get a borrow error:

    error[E0373]: closure may outlive the current function, but it borrows `pool`, which is owned by the current function
       --> src/main.rs:67:18
        |
    67  |     fastcgi::run(|mut req| {
        |                  ^^^^^^^^^ may outlive borrowed value `pool`
    ...
    123 |                 let mut cx = match pool.get_conn() {
        |                                    ---- `pool` is borrowed here
    help: to force the closure to take ownership of `pool` (and any other referenced variables), use the `move` keyword
        |
    67  |     fastcgi::run(move |mut req| {
        |                  ^^^^^^^^^^^^^^